### ISSUE TITLE
That should be aviod all the time.

### ISSUE THREAD

**Issue by ashkmb** [TohidHeshmati/symfony#2]
https://github.com/TohidHeshmati/symfony/blob/5c57b56379866a16b20d137b6816b80db8172538/.env#L18

There are many good articles which blown my mind about this simple mistake but I guess this one is realistic and also optimistic. 

https://dev.to/somedood/please-dont-commit-env-3o9h

You may set up a Documentation system for your self. I Highly recommend [wikijs](https://wiki.js.org/)

**Comment by TohidHeshmati** [comment]
Thanks for noting that out. that's not an issue or security problem. The article you have mentioned didn't point out what is wrong with it and why should be avoided and what kind of data can be extracted. for example in Symfony official docs you can see the same thing but what then?
https://symfony.com/doc/current/configuration.html#listing-environment-variables

Although, this shows the need to an initializer for Symfony same as start.Spring.io for Spring framework.(from my prespective)

This repo is out of date. Wont be updated soon and the System it was running on is not in use anymore. so with no changes I'll close this issue
